util-linux required for /usr/bin/getopt
Unless it's installed a lot of messages:

/bin/vconftool: line 273: getopt: command not found
ERROR: vconftool set: bad arguments

during firmware build

Change-Id: Iebba7a8106e11f44637e313d6a7779fd61aa5db2
Signed-off-by: Vyacheslav Barinov <v.barinov@samsung.com>